In [1]:
# importing of libaries
import numpy as np

In [7]:

arr = np.array([10, 20, 30, 40, 50])
print(arr)
print("Average number", arr.mean())

[10 20 30 40 50]
Average number 30.0


In [9]:
print(arr[0])
print(arr[4])
print(arr[3])
print(arr[2])
print(arr[1])
print(arr[-3])

10
50
40
30
20
30


In [11]:
# slicing
print(arr[1:4])
print(arr[::2])
print(arr[:7])
print(arr[7:])
print(arr[-1:-4])
print(arr[:])
print(arr[-4:-1])
print(arr[4:2])

[20 30 40]
[10 30 50]
[10 20 30 40 50]
[]
[]
[10 20 30 40 50]
[20 30 40]
[]


In [13]:
# creating a 2D array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(matrix[0,1])
print(matrix[:2,0])
print(matrix[1, 0:2])
print(matrix[:, 2])

2
[1 4]
[4 5]
[3 6 9]


In [19]:
# converting 1D array to 2D array
arr2 = np.arange(1, 13)
reshape = arr2.reshape(3,4)
print("Original Array",arr2)
print("Reshape array:\n", reshape)
print(len(arr2))

#convert 2D array to 1D
flatten = reshape.flatten()
print("1D array:",flatten)

Original Array [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshape array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [23]:
#working with mathematical operators 
arr3 = np.array([1, 2, 3, 4, 5])
arr4= np.array([10, 20, 30, 40, 50])
print(arr3 + arr4)
print(arr3 - arr4)
print(arr3 * arr4)
print(arr3 / arr4)

print("Scaler operator :\n")
print(arr3 ** 2)
print(arr4/2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
Scaler operator :

[ 1  4  9 16 25]
[ 5. 10. 15. 20. 25.]
